name: Build Pretendrop

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  linux:
    name: Linux x64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run dist:linux
      - uses: actions/upload-artifact@v4
        with:
          name: pretendrop-linux-x64
          path: release/*

  macos:
    name: macOS ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-15-intel
            arch: x64
          - runner: macos-14
            arch: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run dist:mac
      - uses: actions/upload-artifact@v4
        with:
          name: pretendrop-macos-${{ matrix.arch }}
          path: release/*
