name: Build Pretendrop

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  linux:
    name: Linux x64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run dist:linux
      - uses: actions/upload-artifact@v4
        with:
          name: pretendrop-linux-x64
          path: release/*

  macos:
    name: macOS ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-13
            arch: x64
          - runner: macos-14
            arch: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run dist:mac
      - uses: actions/upload-artifact@v4
        with:
          name: pretendrop-macos-${{ matrix.arch }}
          path: release/*
